blank_issues_enabled: false
contact_links:
  - name: Phidi community on Discord
    url: https://discord.gg/n8tGJ6Rn6D
    about: Please ask and answer questions here.
  - name: Phidi community on Matrix
    url: https://matrix.to/#/#phidi-editor:matrix.org
    about: Please ask and answer questions here.
  - name: Phidi documentation
    url: https://docs.phidi.dev/
    about: Documentation for Phidi
